title: "Elijah Solokhin"
description: "CRM and bussiness automation developer | PHP, JavaScript, Google Apps Script"
description1: "CRM and bussiness automation developer"
description2: "PHP, JavaScript, Google Apps Script"
logo: "spresso-logo.png"

# Your site's domain. E.g: http://yoursite.com
url: "https://data5.pro"

parsedown_actived: true

# Comments in posts
comments:
    enabled: false
    disqus_shortname: solohin

# Information about author
author:
    name: "Elijah Solokhin"

    # Social networks
    twitter:
    github: "https://github.com/solohin"
    bitbucket:
    facebook: "https://www.facebook.com/solohin.i"
    linkedin: "https://www.linkedin.com/in/elijah-solokhin-5a6026a5"
    gplus:
    youtube:

# Collections
collections:
  posts:
    output: true

  projects:
    output: true

# RSS feed
feed:
    max_item: 10

# Facebook Open Graph
open_graph:
    locale: "en_US"

# Code highlight for <pre> and <code> tags
# Powered by http://highlightjs.org/
code_highlight: true

# Site validation
google_verify: rfceqIUY7ZAUfxWs7CxcXcv4SyILjHGwbguK87az7hk
bing_verify:

# Page menus
top_menu:
    - { name: "Google apps script", url: "/categories/google-apps-script/" }
#    - { name: Projects, url: "/projects" }

bottom_menu:
#    - { name: "Go to Spresso theme web", url: "https://github.com/yosymfony/Spress-theme-spresso" }
